# -*- coding: utf-8 -*-
"""Project_IITD.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14PXP3kBWGhEk6uFd7altyT0ss-eBYHve
"""

from google.colab import drive
drive.mount('/content/drive')

!unzip -q "/content/drive/MyDrive/archive.zip" -d "/content/dataset"

import os

print(os.listdir("/content/dataset"))

import pandas as pd

df = pd.read_csv("/content/dataset/styles.csv", on_bad_lines="skip")

print(df.shape)
df.head()

men_tshirt_df = df[
    (df["gender"] == "Men") &
    (df["articleType"] == "Tshirts")
].copy()

print("Total Men's T-shirts:", len(men_tshirt_df))

import os

IMAGE_DIR = "/content/dataset/images"

men_tshirt_df["image_path"] = men_tshirt_df["id"].apply(
    lambda x: os.path.join(IMAGE_DIR, str(x) + ".jpg")
)

men_tshirt_df.head()

men_tshirt_df["exists"] = men_tshirt_df["image_path"].apply(os.path.exists)

print(men_tshirt_df["exists"].value_counts())

men_tshirt_df = men_tshirt_df[men_tshirt_df["exists"] == True].copy()
men_tshirt_df = men_tshirt_df.drop(columns=["exists"])

print("Final Men's T-shirt images:", len(men_tshirt_df))

men_tshirt_df.to_csv("/content/drive/MyDrive/mens_tshirt_dataframe.csv", index=False)

print("Clean DataFrame saved successfully")

from sklearn.model_selection import train_test_split

historical_df, new_market_df = train_test_split(
    men_tshirt_df,
    train_size=3145,
    random_state=42
)

print("Historical:", len(historical_df))
print("New Market:", len(new_market_df))

required_preferred = 1468
required_not_preferred = 1677

preferred_colours = ["Black", "Grey", "Navy Blue", "White", "Blue"]

preferred_pool = historical_df[
    historical_df["baseColour"].isin(preferred_colours)
].copy()

not_preferred_pool = historical_df[
    ~historical_df["baseColour"].isin(preferred_colours)
].copy()

preferred_final = preferred_pool.sample(n=required_preferred, random_state=42)

remaining_needed = required_not_preferred - len(not_preferred_pool)

extra_not_preferred = preferred_pool.drop(preferred_final.index).sample(
    n=remaining_needed,
    random_state=42
)

not_preferred_final = pd.concat(
    [not_preferred_pool, extra_not_preferred],
    ignore_index=True
)

preferred_final["label"] = 1
not_preferred_final["label"] = 0

preference_df = pd.concat(
    [preferred_final, not_preferred_final],
    ignore_index=True
).sample(frac=1, random_state=42).reset_index(drop=True)

print(preference_df["label"].value_counts())
print("Final Historical Dataset:", len(preference_df))

preferred_df = preference_df[preference_df["label"] == 1].copy()
not_preferred_df = preference_df[preference_df["label"] == 0].copy()

train_preferred = preferred_df.sample(n=1049, random_state=42)
test_preferred = preferred_df.drop(train_preferred.index)

negative_examples = not_preferred_df.copy()

train_df = pd.concat([train_preferred, negative_examples], axis=0)
train_df = train_df.sample(frac=1, random_state=42).reset_index(drop=True)

test_df = test_preferred.reset_index(drop=True)

print("Train Preferred:", len(train_preferred))
print("Test Preferred:", len(test_preferred))
print("Negative Examples:", len(negative_examples))

print("\nFinal Train Dataset:", len(train_df))
print("Final Test Dataset:", len(test_df))

print("\nTrain Labels:")
print(train_df["label"].value_counts())

print("\nTest Labels:")
print(test_df["label"].value_counts())

!pip install -q transformers torch pillow tqdm scikit-learn

import torch
import numpy as np
from PIL import Image
from tqdm import tqdm
from transformers import CLIPProcessor, CLIPModel

device = "cuda" if torch.cuda.is_available() else "cpu"
print("Device:", device)

clip_model = CLIPModel.from_pretrained(
    "openai/clip-vit-base-patch32"
).to(device)

clip_processor = CLIPProcessor.from_pretrained(
    "openai/clip-vit-base-patch32"
)

clip_model.eval()

print("CLIP Model Loaded Successfully!")

def make_embeddings_batch(dataframe, batch_size=32):

    embeddings = []

    images = dataframe["image_path"].tolist()

    for i in tqdm(range(0, len(images), batch_size)):

        batch_paths = images[i:i+batch_size]

        batch_images = [
            Image.open(p).convert("RGB") for p in batch_paths
        ]

        inputs = clip_processor(
            images=batch_images,
            return_tensors="pt"
        )

        pixel_values = inputs["pixel_values"].to(device)

        with torch.no_grad():

            outputs = clip_model.vision_model(pixel_values=pixel_values)

            pooled = outputs.pooler_output

            emb = clip_model.visual_projection(pooled)

            emb = emb / emb.norm(dim=-1, keepdim=True)

        embeddings.append(emb.cpu().numpy())

    return np.vstack(embeddings)

train_embeddings = make_embeddings_batch(train_df, batch_size=32)
test_embeddings = make_embeddings_batch(test_df, batch_size=32)
new_market_embeddings = make_embeddings_batch(new_market_df, batch_size=32)

print(train_embeddings.shape)
print(test_embeddings.shape)
print(new_market_embeddings.shape)

from sklearn.linear_model import LogisticRegression

preference_model = LogisticRegression(
    max_iter=1000,
    random_state=42
)

preference_model.fit(
    train_embeddings,
    train_df["label"]
)

print("Preference model trained successfully!")